version: 1
disable_existing_loggers: false
formatters:
  default:
    "()": src.logging_setup.ColorFormatter
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
root:
  level: INFO
  handlers: [console]
loggers:
  uvicorn:
    handlers: [console]
    level: INFO
    propagate: false
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: [console]
    level: INFO
    propagate: false
